version: "3"

services:
  postgres_app:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=swap
      - POSTGRES_PASSWORD=swapSWAPswapSWAP12345
      - POSTGRES_DB=swapdb
    volumes:
      - swapvolume:/var/lib/postgresql/data:rw

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    environment:
      # Change to your desired Redis password
      REDIS_PASSWORD: $2a$20$fsGmYgbReR.kEr4rzoyw6O6xr2AGNr3PLkEAroNQY/dtsoEtcxKke
      REDIS_DB: 1

# para .env de backend
# REDIS_HOST: localhost
# REDIS_PORT: 6379
# REDIS_PASSWORD: $2a$20$fsGmYgbReR.kEr4rzoyw6O6xr2AGNr3PLkEAroNQY/dtsoEtcxKke

volumes:
  swapvolume: